#!/bin/sh

start() {
    git init
    python3 -m venom
}

server() {
    if test $APACHE2 ; then 
        service apache2 restart
        echo "Started..."
    else
        echo "Skipping..."
    fi
}

server
start
